# Generated by Django 3.1.6 on 2021-02-07 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия лота')),
                ('starting_rate', models.IntegerField(verbose_name='Начальная ставка')),
                ('current_rate', models.IntegerField(blank=True, default=0, verbose_name='Текущая ставка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='Lots.category')),
                ('current_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_bets', to=settings.AUTH_USER_MODEL, verbose_name='Текущий покупатель')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_lots', to=settings.AUTH_USER_MODEL, verbose_name='Автор лота')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Lots.lot')),
            ],
        ),
    ]
