# Generated by Django 3.1.6 on 2021-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия лота'),
        ),
    ]
